import 'dart:async';
double tims=20.0;
int you = 10;
int me = 10;
String word = '';
bool you_start = true;
bool computer_start = false;
Timer? timer;
List ints=[];
bool play=true;

List list = [];
List alphabet = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z'
];
List ply = list;
List use = [
  'me',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v'
];

List countries = [
  'afghanistan',
  'albania',
  'algeria',
  'andorra',
  'angola',
  'antigua and barbuda',
  'argentina',
  'armenia',
  'australia',
  'austria',
  'azerbaijan',
  'the bahamas',
  'bahrain',
  'bangladesh',
  'barbados',
  'belarus',
  'belgium',
  'belize',
  'benin',
  'bhutan',
  'bolivia',
  'bosnia and herzegovina',
  'botswana',
  'brazil',
  'brunei',
  'bulgaria',
  'burkina faso',
  'burundi',
  'cabo verde',
  'cambodia',
  'cameroon',
  'canada',
  'central african republic',
  'chad',
  'chile',
  'china',
  'colombia',
  'comoros',
  'democratic republic of congo',
  'costa rica',
  'croatia',
  'cuba',
  'cyprus',
  'czech republic',
  'denmark',
  'djibouti',
  'dominica',
  'dominican republic',
  'east timor',
  'ecuador',
  'egypt',
  'el salvador',
  'equatorial guinea',
  'eritrea',
  'estonia',
  'eswatini',
  'ethiopia',
  'fiji',
  'finland',
  'france',
  'gabon',
  'the gambia',
  'georgia',
  'germany',
  'ghana',
  'greece',
  'grenada',
  'guatemala',
  'guinea',
  'guinea-bissau',
  'guyana',
  'haiti',
  'honduras',
  'hungary',
  'iceland',
  'india',
  'indonesia',
  'iran',
  'iraq',
  'ireland',
  'israel',
  'italy',
  'jamaica',
  'japan',
  'jordan',
  'kazakhstan',
  'kenya',
  'kiribati',
  'north korea',
  'south korea',
  'kosovo',
  'kuwait',
  'kyrgyzstan',
  'la cote divoire',
  'laos',
  'latvia',
  'lebanon',
  'lesotho',
  'liberia',
  'libya',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'madagascar',
  'malawi',
  'malaysia',
  'maldives',
  'mali',
  'malta',
  'marshall islands',
  'mauritania',
  'mauritius',
  'mexico',
  'micronesia, federated states of',
  'moldova',
  'monaco',
  'mongolia',
  'montenegro',
  'morocco',
  'mozambique',
  'myanmar',
  'namibia',
  'nauru',
  'nepal',
  'netherlands',
  'new zealand',
  'nicaragua',
  'niger',
  'nigeria',
  'north macedonia',
  'norway',
  'oman',
  'pakistan',
  'palau',
  'panama',
  'papua new guinea',
  'paraguay',
  'peru',
  'philippines',
  'poland',
  'portugal',
  'qatar',
  'romania',
  'russia',
  'rwanda',
  'saint kitts and nevis',
  'saint lucia',
  'saint vincent and the grenadines',
  'samoa',
  'san marino',
  'sao tome and principe',
  'saudi arabia',
  'senegal',
  'serbia',
  'seychelles',
  'sierra leone',
  'singapore',
  'slovakia',
  'slovenia',
  'solomon islands',
  'somalia',
  'south africa',
  'spain',
  'sri lanka',
  'sudan',
  'sudan, south',
  'suriname',
  'sweden',
  'switzerland',
  'syria',
  'taiwan',
  'tajikistan',
  'tanzania',
  'thailand',
  'tonga',
  'trinidad and tobago',
  'tunisia',
  'turkey',
  'turkmenistan',
  'tuvalu',
  'uganda',
  'ukraine',
  'united arab emirates',
  'united kingdom',
  'united states',
  'uruguay',
  'uzbekistan',
  'vanuatu',
  'vatican city',
  'venezuela',
  'vietnam',
  'yemen',
  'zambia',
  'zimbabwe'
];
List animals = ['duck', 'elephant','pick'];
List elements = [
  'hydrogen',
  'helium',
  'lithium',
  'beryllium',
  'boron',
  'carbon',
  'nitrogen',
  'oxygen',
  'fluorine',
  'neon',
  'sodium',
  'magnesium',
  'aluminum',
  'silicon',
  'phosphorus',
  'sulfur',
  'chlorine',
  'argon',
  'potassium',
  'calcium',
  'scandium',
  'titanium',
  'vanadium',
  'chromium',
  'manganese',
  'iron',
  'cobalt',
  'nickel',
  'copper',
  'zinc',
  'gallium',
  'germanium',
  'arsenic',
  'selenium',
  'bromine',
  'krypton',
  'rubidium',
  'strontium',
  'yttrium',
  'zirconium',
  'niobium',
  'molybdenum',
  'technetium',
  'ruthenium',
  'rhodium',
  'palladium',
  'silver',
  'cadmium',
  'indium',
  'tin',
  'antimony',
  'tellurium',
  'iodine',
  'xenon',
  'cesium',
  'barium',
  'lanthanum',
  'cerium',
  'praseodymium',
  'neodymium',
  'promethium',
  'samarium',
  'europium',
  'gadolinium',
  'terbium',
  'dysprosium',
  'holmium',
  'erbium',
  'thulium',
  'ytterbium',
  'lutetium',
  'hafnium',
  'tantalum',
  'tungsten',
  'rhenium',
  'osmium',
  'iridium',
  'platinum',
  'gold',
  'mercury',
  'thallium',
  'lead',
  'bismuth',
  'polonium',
  'astatine',
  'radon',
  'francium',
  'radium',
  'actinium',
  'thorium',
  'protactinium',
  'uranium',
  'neptunium',
  'plutonium',
  'americium',
  'curium',
  'berkelium',
  'californium',
  'einsteinium',
  'fermium',
  'mendelevium',
  'nobelium',
  'lawrencium',
  'rutherfordium',
  'dubnium',
  'seaborgium',
  'bohrium',
  'hassium',
  'meitnerium',
  'darmstadtium',
  'roentgenium',
  'copernicium',
  'nihonium',
  'flerovium',
  'moscovium',
  'livermorium',
  'tennessine',
  'oganesson'
];
List fruits = [
  'Apple',
  'Apricot',
  'Avocado',
  'Abiu',
  'Acai',
  'Acerola',
  'Ackee',
  'Arhat',
  'American Mayapple',
  'African Cherry Orange',
  'Amazon grape',
  'Araza',
  'Alligator apple',
  'Ambarella',
  'African Cucumber',
  'African Medlar',
  'African Moringa',
  'Agave Plant',
  'Aizen Fruit',
  'American Black Elderberry',
  'American Chestnut',
  'American Hazelnut Shrub',
  'American Red Raspberry',
  'Aprium',
  'Atemoya',
  'Atherton Raspberry',
  'Banana',
  'Berry',
  'Bayberry',
  'Blueberry',
  'Blackberry',
  'Boysenberry',
  'Bearberry',
  'Bilberry',
  'Barberry',
  'Buffaloberry',
  'Black cherry',
  'Beach plum',
  'Black raspberry',
  'Black apple',
  'Blue tongue',
  'Bolwarra',
  'Burdekin plum',
  'Bramble',
  'Broadleaf Bramble',
  'Black mulberry',
  'Blood orange',
  'Babaco',
  'Bael',
  'Barbadine',
  'Barbados cherry',
  'Betel nut',
  'Bilimbi',
  'Bitter gourd',
  'Black sapote',
  'Bottle gourd',
  'Brazil nut',
  'Breadfruit',
  'Burmese grape',
  'Blackcurrant',
  'Bignay',
  'Beechnut',
  'Bacuri Fruit',
  'Balsam Apple',
  'Batuan Fruit',
  'Blood Lime',
  'Brazilian Guava',
  'Brush cherry',
  'Cantaloupe',
  'Chokeberry',
  'Cranberry',
  'Cloudberry',
  'Crowberry',
  'Conkerberry',
  'Calabash',
  'Calamansi',
  'Calamondins',
  'Canistel',
  'Cape Gooseberry',
  'Capuli Cherry',
  'Carob Fruit',
  'Cashew Apple',
  'Cedar Bay Cherry',
  'Cempedak',
  'Ceylon Gooseberry',
  'Charichuelo Fruit',
  'Chayote Fruit',
  'Cherimoya Fruit',
  'cherry Fruit',
  'Chokecherry',
  'Citrofortunella',
  'Clementines',
  'Cluster Fig',
  'Coco Plum',
  'Common Apple Berry',
  'Cornelian Cherry',
  'Cucumber',
  'Cupuacu',
  'Damson',
  'Date plum',
  "Davidson's plum",
  "Dead Man's Fingers",
  'Dekopon',
  'Desert fig',
  'Desert lime',
  'Dodder laurel',
  'Double Coconut',
  'Dragon Fruit',
  'Duku fruit',
  'Durian',
  'Eastern Hawthorn',
  'Elephant apple',
  'Emu Apple',
  'Emu berry',
  'Fairchild tangerine',
  'False mastic',
  'Feijoa',
  'Fibrous Satinash',
  'Finger Lime',
  'Florida strangler fig',
  'Forest strawberries',
  'Gac Fruit',
  'Galia melon',
  'Gambooge',
  'Genip',
  'Giant Granadilla',
  'Golden apple',
  'Goumi Fruit',
  "Governor's Plum",
  'Granadilla',
  'Grapefruit',
  'Grapes',
  'Grapple',
  'Greengage',
  'Ground Plum',
  'Grumichama',
  'Guanabana',
  'Guarana',
  'Guavaberry',
  'Hackberry',
  'Hardy-kiwi',
  'Hawthorn',
  'Honeydew',
  'Honeysuckle',
  'Horned melon',
  'Huckleberry',
  'Huito',
  'Ice Cream Bean',
  'Ilama',
  'Illawarra Plum',
  'Imbe fruit',
  'Indian almond',
  'Indian Fig',
  'Indian Gooseberry',
  'Indian jujube',
  'Indian Prune',
  'Jabotacaba',
  'Jackfruit',
  'Jambul fruit',
  'Japanese Persimmon',
  'Jatoba fruit',
  'Jelly Palm',
  'Jocote',
  'Jostaberry',
  'Jujube',
  'Junglesop',
  'Juniper berry',
  'Kabosu Fruit',
  'Kaffir lime',
  'Kahikatea',
  'Kakadu plum',
  'Kapok',
  'Karkalla',
  'Karonda',
  'Kei apple',
  'Kepel',
  'Keule',
  'Kiwi',
  'Korlan',
  'Kumquat',
  'Kundong',
  'Kutjera',
  'Kwai Muk',
  'Lablab',
  'Lady apple',
  'Lakoocha',
  'Langsat',
  'Lapsi',
  'Lardizabala',
  'Lemato',
  'Lemon aspen',
  'Lemons',
  'Leucaena',
  'Lillypilly',
  'Limeberry',
  'Limequat',
  'Lingonberry',
  'Loganberry',
  'Loquat',
  'Lucuma',
  'Lychee',
  'Macadamia',
  'Madrono',
  'Malay Apple',
  'Mamey Sapote',
  'Mammee Apple',
  'Mamoncillo',
  'Mandarin',
  'Mangaba',
  'Mangosteen',
  'Manila Tamarind',
  'Manoao',
  'Ma-praang',
  'Maqui',
  'Marang',
  'Marionberry',
  'Marula',
  'Mayan Nut',
  'Mayapple',
  'Maypop',
  'Melinjo',
  'MelonPear',
  'Midyim',
  'Miracle fruit',
  'Mock Strawberry',
  'Monstera Delicisiosa',
  'Mora de Castilla',
  'Morinda',
  'Mountain pepper',
  'Mountain Soursop',
  'Muscadine',
  'Naartjie',
  'Nageia',
  'Nance',
  'Naranjilla',
  'Nectacotum',
  'Nectarines',
  'Neem',
  'Nere',
  'Nonda plum',
  'Nungu',
  'Nutmeg',
  'Oil Palm',
  'Olallieberry',
  'Olive',
  'Orangelo',
  'Oranges',
  'Oregon grape',
  'Oroblanco',
  'Ortanique',
  'Otaheite gooseberry',
  'Papaya',
  'Passion Fruit',
  'Peach',
  'Peach palm',
  'Peanut',
  'Pears',
  'Pecan',
  'Pequi',
  'Persian lime',
  'Persimmon',
  'Peumo',
  'Phalsa',
  'Physalis Fruit',
  'Pigeon pea',
  'Pigeon plum',
  'Pigface',
  'Pili Nut',
  'Pine apple',
  'Pineberry',
  'Pink-flowered Native Raspberry',
  'Plum',
  'Plumcot',
  'Pluot',
  'Pomato',
  'Pomegranate',
  'Pulasan',
  'Pummelo',
  'Rambutan',
  'Rangpur',
  'Red Mombin',
  'Riberry',
  'Rollinia',
  'Rose Apple',
  'Safou',
  'Salak',
  'Santol',
  'Sapodilla',
  'Soncoya',
  'Star Apple',
  'Star Fruit',
  'Strawberry guava',
  'Sugar Apple',
  'Sweet Orange',
  'Sweet Pepper',
  'Tamarind',
  'Tangelo',
  'Tangor',
  'Tayberry',
  'Tomato',
  'Ugli',
  'Vanilla',
  'Velvet apple',
  'Walnut',
  'Watermelon',
  'Wax jambu',
  'White sapote',
  'Youngberry',
  'Yuzu'
];
List football = ['ama','kofi','esi','x'];

List play_list(String key) {
  Map x = {
    'Animals': animals,
    'Elements in the periodic table': elements,
    'European football teams': football,
    'Fruits': fruits,
    'Countries': countries

  };
  return x[key];
}

int lust=1;
String first_name='';
String second_name='';
bool first_start=true;
bool second_start=false;

